function udot = cumulant_eqns(u)

udot = zeros(size(u));

f = 1;
faa = 1;
G = 1;
g = 2;
gaa = 2;
n = 1000;
o = 1000;
gs = faa-f;

sp = u(1);
szsp = u(2);
sz = u(3);
spsm = u(4);
szsz = u(5);
spsp = u(6);

udot(1,1) = (0.E-307+sqrt(-1)*0.5E0).*G.*gaa.*sp+(-1/2).*G.*(f+gs).*sp+( ...
0.E-307+sqrt(-1)*(-0.5E0)).*o.*sz+0.5E0.*(f+(sqrt(-1)*(-1)).*g).* ...
  G.*((-1)+n).*szsp;

udot(2,1) = (-1/2).*(f+sqrt(-1).*g).*G.*sp+(-1).*G.*(f+gs).*sp+(-1).*f.*G.* ...
szsp+(0.E-307+sqrt(-1)*0.5E0).*G.*gaa.*szsp+(-3/2).*G.*(f+gs).* ...
szsp+(1/2).*(f+(sqrt(-1)*(-1)).*g).*G.*((-2)+n).*((-2).*sp.*sz.^2+ ...
  2.*sz.*szsp+sp.*szsz)+(-1).*(f+sqrt(-1).*g).*G.*((-2)+n).*(2.*sp.* ...
  spsm+(-2).*sp.^2.*Conjugate(sp)+spsp.*Conjugate(sp))+(0.E-307+ ...
 sqrt(-1)*(-0.5E0)).*o.*(szsz+2.*(spsp+(-1).*Conjugate(spsm)))+(-1) ...
  .*(f+(sqrt(-1)*(-1)).*g).*G.*((-2)+n).*(sp.*spsm+(-2).*sp.^2.* ...
 Conjugate(sp)+spsp.*Conjugate(sp)+sp.*Conjugate(spsm));

udot(3,1) = (-1).*G.*(f+gs)+(-1).*G.*(f+gs).*sz+(sqrt(-1)*(-1)).*o.*(sp+(-1).* ...
  Conjugate(sp))+2.*g.*G.*((-1)+n).*imag(spsm)+(-2).*f.*G.*((-1)+n).* ...
  real(spsm);

udot(4,1) = (-1).*G.*(f+gs).*spsm+(1/2).*f.*G.*(sz+szsz)+(0.E-307+sqrt(-1)*( ...
  -0.5E0)).*o.*((-1).*szsp+Conjugate(szsp))+(1/2).*(f+sqrt(-1).*g).* ...
  G.*((-2)+n).*(spsm.*sz+(-2).*sp.*sz.*Conjugate(sp)+szsp.* ...
  Conjugate(sp)+sp.*Conjugate(szsp))+(1/2).*(f+(sqrt(-1)*(-1)).*g).* ...
  G.*((-2)+n).*((-2).*sp.*sz.*Conjugate(sp)+szsp.*Conjugate(sp)+sz.* ...
  Conjugate(spsm)+sp.*Conjugate(szsp));

udot(5,1) = (-2).*G.*(f+gs).*sz+(-2).*G.*(f+gs).*szsz+(sqrt(-1)*(-2)).*o.*( ...
  szsp+(-1).*Conjugate(szsp))+4.*f.*G.*real(spsm)+(-4).*G.*((-2)+n).* ...
  real((f+sqrt(-1).*g).*(spsm.*sz+(-2).*sp.*sz.*Conjugate(sp)+szsp.* ...
  Conjugate(sp)+sp.*Conjugate(szsp)));

udot(6,1) = sqrt(-1).*G.*gaa.*spsp+(-1).*G.*(f+gs).*spsp+(sqrt(-1)*(-1)).*o.* ...
  szsp+(f+(sqrt(-1)*(-1)).*g).*G.*((-2)+n).*((-2).*sp.^2.*sz+spsp.* ...
  sz+2.*sp.*szsp);


end

function zc = Conjugate(z)
zc = z';
end